
**Organization, Themes, and HTML Output**

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(forcats)
library(devtools)
library(ggforce)
library(gridExtra)
kspatel_315_theme <-  theme_bw() + # White background, black and white theme
  theme(axis.text = element_text(size = 12, color = "firebrick3"),
        text = element_text(size = 14, face = "bold", color = "dodgerblue4"))

#  Colorblind-friendly color pallette
my_colors <- c("#000000", "#56B4E9", "#E69F00", "#F0E442", "#009E73", "#0072B2", 
               "#D55E00", "#CC7947")
```


```{r, warning = F, message = F}
#crime <- read_csv("https://raw.githubusercontent.com/kishan/SF-Crime-Analysis/master/crime.csv")
crime <- read_csv("crime.csv")

library(dplyr)
library(readr)
library(lubridate)

coltypes <-
    list(Dates = col_datetime("%Y-%m-%d %H:%M:%S"))

train <- crime

train <-
    train %>%
    mutate(Year  = factor(year(Dates), levels=2003:2015),
           Month = factor(month(Dates), levels=1:12),
           Day   = day(Dates),
           Hour  = factor(hour(Dates), levels=0:23),
           dayDate = as.POSIXct(round(Dates, units = "days")),
           DayOfWeek = factor(DayOfWeek, levels=c("Monday",
                                                  "Tuesday",
                                                  "Wednesday",
                                                  "Thursday",
                                                  "Friday",
                                                  "Saturday",
                                                  "Sunday"))
           )
           
unique(train$Category)
sort(table(train$Category))

```

```{r, warning = F, message = F}
library(ggmap)
# map <- readRDS("../input/sf_map_copyright_openstreetmap_contributors.rds")
map<-get_map(location="sanfrancisco", zoom=12, source="google", color = "bw")

train_scat <- head(train, 10000)
#train_scat <- train
counts <- summarise(group_by(train_scat, Category), Counts=length(Category))
counts <- counts[order(-counts$Counts),]
# This removes the "Other Offenses" category
top12_cats_to_keep <- counts$Category[c(1,3:13)]
top12 <- train_scat[train_scat$Category %in% top12_cats_to_keep,]

p <- ggmap(map) +
     geom_point(data=top12, aes(x=X, y=Y, color=factor(Category)), alpha=0.3, size = 1) +
     guides(colour = guide_legend(override.aes = list(alpha=1.0, size=4.0),
                                  title="Type of Crime")) +
     scale_colour_brewer(type="qual",palette="Paired") + 
     ggtitle("Top Crimes in San Francisco") +
     theme_light(base_size=10) +
     kspatel_315_theme + 
     theme(axis.line=element_blank(),
           axis.text.x=element_blank(),
           axis.text.y=element_blank(),
           axis.ticks=element_blank(),
           axis.title.x=element_blank(),
           axis.title.y=element_blank())
p
```

```{r, warning = F, message = F}
mapdata <-
    train %>%
    filter(Category %in% c("ASSAULT", "ROBBERY", "SEX OFFENSES FORCIBLE"))

mapdata <-
    train

mapdata %>%
group_by(Category) %>%
summarise(n=n())

contours <- stat_density2d(aes(x = X, y = Y, 
                               fill = ..level.., 
                               alpha=..level..),
                           size = 0.1, 
                           data = mapdata, 
                           n=200,
                           geom = "polygon")

ggmap(map, extent='device', legend="topleft") + 
  contours +
  scale_alpha_continuous(range=c(0.25,0.4), guide='none') +
  scale_fill_gradient('Violent\nCrime\nDensity', low = "blue", high = "red")+
  ggtitle('Violent Crime in San Francisco')
```